

import UIKit

struct TrainingModelCS {
    let title: String
    let description: String
    let duration: Int
}

let workouts: [TrainingModelCS] = [
    TrainingModelCS(title: "Balance on One Leg", description: "Hold your balance on one leg without touching the ground.", duration: 20),
    TrainingModelCS(title: "Jumping in Place", description: "Jump continuously in place without stopping.", duration: 40),
    TrainingModelCS(title: "Squats", description: "Perform controlled squats, keeping your back straight.", duration: 45),
    TrainingModelCS(title: "Push-ups", description: "Do as many push-ups as possible with proper form.", duration: 30),
    TrainingModelCS(title: "Running in Place", description: "Run on the spot with a steady pace.", duration: 60),
    TrainingModelCS(title: "Plank Hold", description: "Hold a plank position, keeping your core engaged.", duration: 60),
    TrainingModelCS(title: "High Knees", description: "Lift your knees up to waist level while running in place.", duration: 40),
    TrainingModelCS(title: "Burpees", description: "Perform continuous burpees, including a push-up and jump.", duration: 45),
    TrainingModelCS(title: "Spinal Stretch", description: "Stretch your back by bending forward and reaching your toes.", duration: 60),
    TrainingModelCS(title: "One-Leg Hops", description: "Hop on one leg continuously, then switch sides.", duration: 30),
    TrainingModelCS(title: "Bicycle Crunches", description: "Perform bicycle-style crunches for core activation.", duration: 60),
    TrainingModelCS(title: "Leg Swings", description: "Swing your legs forward and backward to stretch your hips.", duration: 45),
    TrainingModelCS(title: "Jump Rope Simulation", description: "Mimic jump rope movements without an actual rope.", duration: 60),
    TrainingModelCS(title: "Side Plank Hold", description: "Hold a side plank position, then switch sides.", duration: 30),
    TrainingModelCS(title: "Lunges", description: "Step forward into lunges, alternating legs.", duration: 60),
    TrainingModelCS(title: "Side-to-Side Jumps", description: "Jump laterally from side to side.", duration: 45),
    TrainingModelCS(title: "Jump Squats", description: "Perform squats with an explosive jump.", duration: 40),
    TrainingModelCS(title: "Pull-ups", description: "Do as many pull-ups as possible with proper form.", duration: 30),
    TrainingModelCS(title: "Arm Raises", description: "Raise and lower your arms repeatedly.", duration: 45),
    TrainingModelCS(title: "Boat Pose Hold", description: "Hold the boat pose while engaging your core.", duration: 40),
    TrainingModelCS(title: "Sit-ups", description: "Perform controlled sit-ups, engaging your abs.", duration: 60),
    TrainingModelCS(title: "Push-up Hold", description: "Hold the bottom position of a push-up.", duration: 40),
    TrainingModelCS(title: "Sprint Intervals", description: "Alternate between slow running and sprinting.", duration: 45),
    TrainingModelCS(title: "Side Bends", description: "Perform side bends to stretch your obliques.", duration: 60),
    TrainingModelCS(title: "Wall Sit", description: "Hold a sitting position against a wall.", duration: 45),
    TrainingModelCS(title: "Leg Hold", description: "Keep your legs raised above the ground.", duration: 40),
    TrainingModelCS(title: "Toe Raises", description: "Lift your heels off the ground repeatedly.", duration: 60),
    TrainingModelCS(title: "Clapping Push-ups", description: "Perform push-ups with a clap at the top.", duration: 30),
    TrainingModelCS(title: "Toe Touches", description: "Reach for your toes while standing.", duration: 45),
    TrainingModelCS(title: "Duck Walk", description: "Walk forward in a squat position.", duration: 60),
    TrainingModelCS(title: "Pause Squats", description: "Hold a squat at the bottom position.", duration: 40),
    TrainingModelCS(title: "Jump Out of Squat", description: "Perform an explosive jump from a squat.", duration: 45),
    TrainingModelCS(title: "Plank with Arm Raises", description: "Hold a plank while lifting alternating arms.", duration: 60),
    TrainingModelCS(title: "Bridge Hold", description: "Keep your hips elevated in a bridge position.", duration: 40),
    TrainingModelCS(title: "Superman Hold", description: "Lie on your stomach and lift your arms and legs.", duration: 45),
    TrainingModelCS(title: "Leg Raises", description: "Lift both legs while lying on your back.", duration: 60),
    TrainingModelCS(title: "Side Lunges", description: "Step to the side into a deep lunge.", duration: 40),
    TrainingModelCS(title: "Twisting Crunches", description: "Rotate your torso while doing crunches.", duration: 60),
    TrainingModelCS(title: "Invisible line jumps", description: "Jump forward and backward over an imaginary line.", duration: 45),
    TrainingModelCS(title: "Squats with knee lifts", description: "Squat down and lift one knee when standing up.", duration: 60),
    TrainingModelCS(title: "Shoulder taps in plank", description: "Tap your shoulders while holding a plank.", duration: 40),
    TrainingModelCS(title: "Heel kicks", description: "Run in place, kicking your heels to your glutes.", duration: 45),
    TrainingModelCS(title: "Vertical jumps", description: "Jump as high as possible repeatedly.", duration: 60),
    TrainingModelCS(title: "Warrior pose hold", description: "Hold the warrior yoga pose.", duration: 45),
    TrainingModelCS(title: "Squats with floor tap", description: "Squat down and touch the ground with your hands.", duration: 60),
    TrainingModelCS(title: "Mountain climbers", description: "Bring your knees to your chest while in a plank.", duration: 40),
    TrainingModelCS(title: "Narrow push-ups", description: "Perform push-ups with hands close together.", duration: 45),
    TrainingModelCS(title: "Reverse lunges", description: "Step backward into lunges.", duration: 60),
    TrainingModelCS(title: "Arm circles", description: "Make circular movements with your arms.", duration: 40),
    TrainingModelCS(title: "Jump with a twist", description: "Jump and rotate your torso mid-air.", duration: 45),
    TrainingModelCS(title: "Forward bends", description: "Bend forward and touch your toes.", duration: 60),
    TrainingModelCS(title: "Fast arm rotations", description: "Rotate your arms quickly in small circles.", duration: 45),
    TrainingModelCS(title: "Side crunches", description: "Perform crunches while twisting to the side.", duration: 60),
    TrainingModelCS(title: "Tip-toe balance", description: "Stand on your tiptoes and hold balance.", duration: 40),
    TrainingModelCS(title: "Shoulder stretches", description: "Extend and stretch your shoulders.", duration: 45),
    TrainingModelCS(title: "Star jumps", description: "Jump with arms and legs spread out.", duration: 60),
    TrainingModelCS(title: "March in place", description: "Lift knees while marching in place.", duration: 40),
    TrainingModelCS(title: "Slow negative push-ups", description: "Lower yourself down slowly in a push-up.", duration: 45),
    TrainingModelCS(title: "Glute bridge pulses", description: "Perform small pulsing movements in a bridge position.", duration: 60),
    TrainingModelCS(title: "Leg holds at 90 degrees", description: "Keep legs raised at a right angle.", duration: 40),
    TrainingModelCS(title: "Pistol squats", description: "Perform one-legged squats.", duration: 45),
    TrainingModelCS(title: "Jumping lunges", description: "Switch legs mid-air while lunging.", duration: 60),
    TrainingModelCS(title: "Plank with knee taps", description: "Tap your knees to the floor while in a plank.", duration: 40),
    TrainingModelCS(title: "Jumping jacks", description: "Perform continuous jumping jacks.", duration: 45),
    TrainingModelCS(title: "Lunge with floor touch", description: "Touch the floor with your hand while lunging.", duration: 60),
    TrainingModelCS(title: "Lateral leg swings", description: "Swing legs sideways while standing.", duration: 40),
    TrainingModelCS(title: "Plank step-backs", description: "Step your feet back and forth in a plank.", duration: 45),
    TrainingModelCS(title: "Hanging leg raises", description: "Raise your legs while hanging.", duration: 60),
    TrainingModelCS(title: "Leg circles", description: "Move your legs in circular motions while lying down.", duration: 40),
    TrainingModelCS(title: "Squats with feet together", description: "Perform squats with feet touching.", duration: 45),
    TrainingModelCS(title: "Single-leg side jumps", description: "Jump laterally on one leg.", duration: 60),
    TrainingModelCS(title: "Crunches with arm reach", description: "Reach your arms forward while crunching.", duration: 40),
    TrainingModelCS(title: "Squat walk", description: "Move forward while staying in a squat position.", duration: 45),
    TrainingModelCS(title: "Leg lifts while lying down", description: "Keep legs raised off the ground.", duration: 60),
    TrainingModelCS(title: "Clap jumps", description: "Jump while clapping below your knees.", duration: 40),
    TrainingModelCS(title: "Jumping plank jacks", description: "Jump your feet in and out while holding a plank.", duration: 45),
    TrainingModelCS(title: "Side leg raises", description: "Lift one leg to the side while standing.", duration: 60),
    TrainingModelCS(title: "Bridge hold with alternating leg lifts", description: "Hold a bridge while lifting legs.", duration: 40),
    TrainingModelCS(title: "Knee drives in plank", description: "Bring knees to chest while in a plank.", duration: 45),
    TrainingModelCS(title: "Sprint in place", description: "Run as fast as possible in place.", duration: 60),
    TrainingModelCS(title: "Elevated push-ups", description: "Perform push-ups with feet elevated.", duration: 40),
    TrainingModelCS(title: "Side knee crunches", description: "Crunch your knees toward your chest from the side.", duration: 45),
    TrainingModelCS(title: "Plank with leg raises", description: "Lift legs while holding a plank.", duration: 60),
    TrainingModelCS(title: "Jumping sumo squats", description: "Jump into a wide squat stance.", duration: 40),
    TrainingModelCS(title: "Toe taps in plank", description: "Tap your toes side to side while in a plank.", duration: 45),
    TrainingModelCS(title: "Squat pulses", description: "Perform small pulsing movements in a squat.", duration: 60),
    TrainingModelCS(title: "Knee-to-elbow crunches", description: "Bring your knee to the opposite elbow.", duration: 40),
    TrainingModelCS(title: "Jumping heel taps", description: "Jump and tap your heels together mid-air.", duration: 45),
    TrainingModelCS(title: "Plank to push-up", description: "Move from a forearm plank to a push-up position.", duration: 60),
    TrainingModelCS(title: "Jumping front kicks", description: "Perform continuous front kicks while bouncing.", duration: 40)
]
